version: "3.7"

services:

  webserver:
    image: mynamespace/nginx
    build: ./nginx
# Just for debugging purposes
#    entrypoint:
#      - tail
#      - -f
#      - /dev/null
    depends_on:
      - application
    ports:
      - "80:80"
    networks:
      - app
    
  application:
    image: mynamespace/myapp
    build: ./myApp
# Just for debugging purposes
#    entrypoint:
#      - tail
#      - -f
#      - /dev/null
    networks:
      - app

networks:
  app:
    driver: bridge
