version: '3.7'

services:
  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 1
        window: 120s
      placement:
        constraints:
          - node.role == manager
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - mysql
    deploy:
      replicas: 1
networks:
  mysql:
volumes:
  mysql-data:
